### ISSUE TITLE
use dehydrated -c -g for cron runs

### ISSUE THREAD

**Issue by ToeiRei** [loewexy/pdns-acme#5] opened 2018-11-13 17:11 UTC
As dehydrated bails out on errors and stops, it would be nice to have -g passed on to dehydrated to process the remaining entries in case of an API hickup at letsencrypt.

```
 --keep-going (-g)                Keep going after encountering an error while creating/renewing multiple certificates in cron mode
```

**Comment by loewexy** [comment] 2020-09-13 09:43
I do not see why this is required. If you setup the cronjob to run once a day as I recommend it will be done 24h later. If letsencrypt has a hickup it is safe to assume the issue is fixed by now. And dehydrated renews certificates by default if they expire in the next 30 days. So there are 30 tries until a cert is expired.

**Closed by loewexy** 2020-09-13 09:43 UTC
